name: posts_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dart_mappable: ^4.6.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  dart_mappable_builder: ^4.6.1

flutter:
  uses-material-design: true
